<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-10 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 21, 57, 11, 697313, tzinfo=datetime.timezone.utc)),
        ),
    ]
=======
# Generated by Django 5.2.5 on 2025-08-10 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 21, 57, 11, 697313, tzinfo=datetime.timezone.utc)),
        ),
    ]
>>>>>>> ce9b6cf0d7419a255b6a02052dd9479b3d9629be
