<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('non_technical', 'Non-Technical')], default='technical', max_length=20),
        ),
    ]
=======
# Generated by Django 5.2.5 on 2025-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('non_technical', 'Non-Technical')], default='technical', max_length=20),
        ),
    ]
>>>>>>> ce9b6cf0d7419a255b6a02052dd9479b3d9629be
