<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_certificate_certificate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
=======
# Generated by Django 5.2.5 on 2025-08-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_certificate_certificate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
>>>>>>> ce9b6cf0d7419a255b6a02052dd9479b3d9629be
