<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_event_status_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
=======
# Generated by Django 5.2.5 on 2025-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_event_status_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
>>>>>>> ce9b6cf0d7419a255b6a02052dd9479b3d9629be
