<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_event_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'user')},
        ),
    ]
=======
# Generated by Django 5.2.5 on 2025-08-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_event_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'user')},
        ),
    ]
>>>>>>> ce9b6cf0d7419a255b6a02052dd9479b3d9629be
