<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_eventregistration_responses_customfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='responses',
        ),
        migrations.AddField(
            model_name='registration',
            name='responses',
            field=models.JSONField(default=dict),
        ),
    ]
=======
# Generated by Django 5.2.5 on 2025-08-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_eventregistration_responses_customfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='responses',
        ),
        migrations.AddField(
            model_name='registration',
            name='responses',
            field=models.JSONField(default=dict),
        ),
    ]
>>>>>>> ce9b6cf0d7419a255b6a02052dd9479b3d9629be
